// Generated by CoffeeScript 1.3.3
(function() {

  define(['components/Vector2D/Vector2D', 'behaviors/Position', 'components/underscore/underscore'], function(Vector2D, Position) {
    var CalcMapPosition;
    return CalcMapPosition = (function() {

      CalcMapPosition.name = 'calcMapPosition';

      CalcMapPosition.single = true;

      CalcMapPosition.calcMapPos = function(obj, map, cellSize) {
        return obj.pos.clone().divide(cellSize).add(map.size.clone().divideScalar(2).addScalar(-0.5)).round();
      };

      function CalcMapPosition(model) {
        this.model = model;
        this.model.use(Position);
        this.model.map = this.model.config.map;
        this.model.cellSize = this.model.config.cellSize;
        this.model.calcMapPos = function() {
          return CalcMapPosition.calcMapPos(model, model.map, model.cellSize);
        };
      }

      CalcMapPosition.prototype.update = function() {};

      return CalcMapPosition;

    })();
  });

}).call(this);
