// Generated by CoffeeScript 1.3.3
(function() {

  define(['behaviors/Position'], function(Position) {
    var Layer;
    return Layer = (function() {

      Layer.name = 'layer';

      Layer.defaults = {
        layerConfig: {},
        layerClass: null
      };

      function Layer(model) {
        var _layerClass, _layerConfig;
        this.model = model;
        this.model.use(Position);
        if (this.model.config.layer) {
          this.model.layer = this.model.config.layer;
        } else {
          _layerConfig = _.extend({}, Layer.defaults.layerConfig, this.model.config.layerConfig);
          _layerClass = this.model.config.layerClass || Layer.defaults.layerClass;
          this.model.layer = new _layerClass(_layerConfig);
        }
        this.model.layer.pos = this.model.pos;
      }

      Layer.prototype.destructor = function() {
        return this.model.layer.destructor();
      };

      return Layer;

    })();
  });

}).call(this);
