// Generated by CoffeeScript 1.3.3
(function() {

  define([], function() {
    var LifeTime;
    return LifeTime = (function() {

      LifeTime.name = 'lifeTime';

      LifeTime.single = true;

      function LifeTime(model) {
        this.model = model;
        if (this.model.config.lifeTime) {
          this.model.lifeTime = this.model.config.lifeTime;
          setTimeout((function() {
            return this.model.destructor();
          }), this.model.config.lifeTime);
        }
      }

      return LifeTime;

    })();
  });

}).call(this);
