// Generated by CoffeeScript 1.3.3
(function() {

  define(['components/Vector2D/Vector2D', 'behaviors/Position'], function(Vector2D, Position) {
    var Moving;
    return Moving = (function() {

      Moving.name = 'moving';

      Moving.single = true;

      function Moving(model) {
        this.model = model;
        this.model.use(Position);
        this.model.speed = Vector2D.cloneFrom(this.model.config.speed || Vector2D.zero);
      }

      Moving.prototype.update = function() {
        return this.model.pos.add(this.model.speed);
      };

      return Moving;

    })();
  });

}).call(this);
