// Generated by CoffeeScript 1.3.3
(function() {

  define(['components/Vector2D/Vector2D', 'behaviors/Position', 'components/underscore/underscore'], function(Vector2D, Position) {
    var PlatformerWalker;
    return PlatformerWalker = (function() {

      PlatformerWalker.name = 'platformerWalker';

      PlatformerWalker.single = true;

      PlatformerWalker.defaults = {
        walkSpeed: 5
      };

      function PlatformerWalker(model) {
        this.model = model;
        this.model.use(Position);
        this.model.walkSpeed = this.model.config.walkSpeed || PlatformerWalker.defaults.walkSpeed;
        this.model.jumpSpeed = this.model.config.jumpSpeed || PlatformerWalker.defaults.jumpSpeed;
        this.model.direction = new Vector2D(Math.random() < 0.5 ? {
          x: -1,
          y: 0
        } : {
          x: 1,
          y: 0
        });
        _.extend(this.model, this.methods);
      }

      PlatformerWalker.prototype.methods = {
        turnAround: function() {
          if (this.direction === 'left') {
            return this.direction = 'right';
          } else {
            return this.direction = 'left';
          }
        },
        walkLeft: function() {
          this.direction = "left";
          return this.pos.x -= this.walkSpeed;
        },
        walkRight: function() {
          this.direction = "right";
          return this.pos.x += this.walkSpeed;
        }
      };

      return PlatformerWalker;

    })();
  });

}).call(this);
