// Generated by CoffeeScript 1.3.3
(function() {

  define(['components/Vector2D/Vector2D'], function(Vector2D) {
    var Position;
    return Position = (function() {

      Position.name = 'position';

      Position.single = true;

      function Position(model) {
        this.model = model;
        this.model.pos = Vector2D.cloneFrom(this.model.config.pos || Vector2D.zero);
      }

      return Position;

    })();
  });

}).call(this);
