// Generated by CoffeeScript 1.3.3
(function() {

  define(['components/Vector2D/Vector2D', 'behaviors/Position'], function(Vector2D, Position) {
    var Shooter;
    return Shooter = (function() {

      Shooter.name = 'shooter';

      Shooter.single = true;

      Shooter.defaults = {
        shootingDelay: 40
      };

      function Shooter(model) {
        this.model = model;
        this.model.use(Position);
        this.model.shootingDelay = this.model.config.shootingDelay || Shooter.defaults.shootingDelay;
        this.model._canShoot = true;
        this.model._restoreCanShoot = function() {
          return model._canShoot = true;
        };
        _.extend(this.model, this.methods);
      }

      Shooter.prototype.methods = {
        shoot: function() {
          var directionVector;
          if (this._canShoot) {
            directionVector = this.direction === "left" ? {
              x: -1,
              y: 0
            } : {
              x: 1,
              y: 0
            };
            this.createBullet(this.pos, directionVector);
            this._canShoot = false;
            return setTimeout(this._restoreCanShoot, this.shootingDelay);
          }
        }
      };

      return Shooter;

    })();
  });

}).call(this);
