// Generated by CoffeeScript 1.3.3
(function() {

  define(['components/Vector2D/Vector2D'], function(Vector2D) {
    var Size;
    return Size = (function() {

      Size.name = 'size';

      Size.single = true;

      function Size(model) {
        this.model = model;
        this.model.size = Vector2D.cloneFrom(this.model.config.size || Vector2D.zero);
      }

      return Size;

    })();
  });

}).call(this);
