// Generated by CoffeeScript 1.3.3
(function() {

  define([], function() {
    var Unit;
    return Unit = (function() {
      var _defaults;

      _defaults = {
        hp: 10,
        damage: 1
      };

      Unit.name = 'unit';

      Unit.single = true;

      Unit.defaults = _defaults;

      function Unit(model) {
        this.model = model;
        this.model.hp = this.model.config.hp || _defaults.hp;
        this.kills = this.model.config.kills || 0;
        this.damage = this.model.config.damage || _defaults.damage;
        _.extend(this.model, this.methods);
      }

      Unit.prototype.methods = {
        kill: function(unit) {
          unit.die();
          return this.kills++;
        },
        die: function() {
          return this.destructor();
        },
        attack: function(unit) {
          return unit.getHurt(this.damage);
        },
        hetHurt: function(damage) {
          return this.hp -= damage;
        }
      };

      Unit.prototype.update = function() {
        if (this.model.hp < 0) {
          return this.model.die();
        }
      };

      return Unit;

    })();
  });

}).call(this);
