// Generated by CoffeeScript 1.3.3
(function() {

  define(['components/Vector2D/Vector2D', 'behaviors/PlatformerWalker', 'components/underscore/underscore'], function(Vector2D, PlatformerWalker) {
    var PlatformerWalkerAI;
    return PlatformerWalkerAI = (function() {

      PlatformerWalkerAI.name = 'platformerWalkerAI';

      PlatformerWalkerAI.single = true;

      function PlatformerWalkerAI(model) {
        this.model = model;
        this.model.use(PlatformerWalker);
        _.extend(this.model, this.methods);
      }

      PlatformerWalkerAI.prototype.update = function() {
        if (Math.random() < 0.01) {
          this.model.jump();
        }
        this.model.walk();
        if (this.model.direction === "left" && this.model.collisions.left) {
          this.model.turnAround();
        }
        if (this.model.direction === "right" && this.model.collisions.right) {
          return this.model.turnAround();
        }
      };

      PlatformerWalkerAI.prototype.methods = {
        walk: function() {
          if (this.direction === 'left') {
            return this.walkLeft();
          } else {
            return this.walkRight();
          }
        }
      };

      return PlatformerWalkerAI;

    })();
  });

}).call(this);
