// Generated by CoffeeScript 1.3.3
(function() {

  define(['keyboard'], function(keyboard) {
    var PlatformerKeyboard;
    return PlatformerKeyboard = (function() {

      PlatformerKeyboard.single = true;

      PlatformerKeyboard.name = 'platformerKeyboardController';

      function PlatformerKeyboard(model) {
        this.model = model;
      }

      PlatformerKeyboard.prototype.update = function() {
        if (keyboard.up) {
          this.model.jump();
        }
        if (keyboard.left) {
          this.model.walkLeft();
        }
        if (keyboard.right) {
          this.model.walkRight();
        }
        if (keyboard.ctrl) {
          return this.model.shoot();
        }
      };

      return PlatformerKeyboard;

    })();
  });

}).call(this);
