// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['GameObject', 'behaviors/Moving', 'behaviors/Layer', 'GameObjectCollection'], function(GameObject, Moving, Layer, GameObjectCollection) {
    var DynamicGameObject;
    return DynamicGameObject = (function(_super) {

      __extends(DynamicGameObject, _super);

      DynamicGameObject.collection = new GameObjectCollection();

      function DynamicGameObject(config) {
        DynamicGameObject.__super__.constructor.call(this, config);
        DynamicGameObject.collection.push(this);
        this.use(Moving);
        this.use(Layer);
        this;

      }

      return DynamicGameObject;

    })(GameObject);
  });

}).call(this);
