// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define([], function() {
    var CollectionBehavior, GameObjectCollection;
    CollectionBehavior = (function() {

      CollectionBehavior.name = 'collection';

      CollectionBehavior.single = false;

      function CollectionBehavior(model, collection) {
        this.model = model;
        this.collection = collection;
      }

      CollectionBehavior.prototype.destructor = function() {
        return this.collection.remove(this.model);
      };

      return CollectionBehavior;

    })();
    return GameObjectCollection = (function(_super) {

      __extends(GameObjectCollection, _super);

      function GameObjectCollection(items) {
        var item, _i, _len;
        if (items == null) {
          items = [];
        }
        GameObjectCollection.__super__.constructor.call(this);
        for (_i = 0, _len = items.length; _i < _len; _i++) {
          item = items[_i];
          this.push(item);
        }
      }

      GameObjectCollection.prototype.push = function(item) {
        item.use(CollectionBehavior, this);
        return GameObjectCollection.__super__.push.call(this, item);
      };

      GameObjectCollection.prototype.remove = function(item) {
        return this.splice(this.indexOf(item), 1);
      };

      return GameObjectCollection;

    })(Array);
  });

}).call(this);
