// Generated by CoffeeScript 1.3.3
(function() {

  define([], function() {
    var k;
    k = {
      keyNames: [],
      onKeyDown: function(e) {
        console.log(e.keyCode);
        return k[k.keyNames[e.keyCode]] = true;
      },
      onKeyUp: function(e) {
        return k[k.keyNames[e.keyCode]] = false;
      },
      init: function() {
        document.onkeydown = this.onKeyDown;
        return document.onkeyup = this.onKeyUp;
      }
    };
    k.keyNames[32] = "space";
    k.keyNames[37] = "left";
    k.keyNames[38] = "up";
    k.keyNames[39] = "right";
    k.keyNames[40] = "down";
    k.keyNames[13] = "enter";
    k.keyNames[17] = "ctrl";
    return k;
  });

}).call(this);
