// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['GameObject', 'components/Vector2D/Vector2D'], function(GameObject, Vector2D) {
    var Unit;
    return Unit = (function(_super) {

      __extends(Unit, _super);

      function Unit(config) {
        Unit.__super__.constructor.call(this, config);
        this.use(Size);
        this.use(Position);
        this;

      }

      return Unit;

    })(GameObject);
  });

}).call(this);
