// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['GameObject', 'components/Vector2D/Vector2D'], function(GameObject, Vector2D) {
    var Unit;
    return Unit = (function(_super) {
      var defaults;

      __extends(Unit, _super);

      defaults = [
        {
          walkSpeed: 5,
          jumpSpeed: -11.5
        }
      ];

      function Unit(config) {
        this.walkSpeed = config.walkSpeed || defaults.walkSpeed;
        this.jumpSpeed = config.jumpSpeed || defaults.jumpSpeed;
        this.speed = Vector2D.cloneFrom(config.speed || Vector2D.zero);
        Unit.__super__.constructor.call(this, config);
      }

      Unit.prototype.walkLeft = function() {
        this.speed.x -= this.walkSpeed;
        return this;
      };

      Unit.prototype.walkRight = function() {
        this.speed.x = this.walkSpeed;
        return this;
      };

      Unit.prototype.jump = function() {
        return this.speed.y = this.jumpSpeed;
      };

      return Unit;

    })(GameObject);
  });

}).call(this);
